import type { GrantCategory, Purpose } from '@/lib/types';

export type SearchConsoleOpportunity = {
  label: string;
  description: string;
  href: string;
  intent: '生活支援' | '子育て' | '介護' | '住まい' | '学び' | '医療';
  observedQuery: string;
  categories: GrantCategory[];
  purposes: Purpose[];
  prefectures?: string[];
  municipalities?: string[];
  grantSlugs?: string[];
  seoTitle?: string;
  metaDescription?: string;
  shortAnswer?: string;
};

export const SEARCH_CONSOLE_OPPORTUNITIES: SearchConsoleOpportunity[] = [
  {
    label: '釧路市の補助金・助成金・給付金',
    description: '釧路市の制度を、対象者、目的、制度種別、受付状況からまとめて確認できます。',
    href: '/municipality/%E5%8C%97%E6%B5%B7%E9%81%93/%E9%87%A7%E8%B7%AF%E5%B8%82/',
    intent: '生活支援',
    observedQuery: '釧路 補助金',
    categories: ['living', 'childcare', 'housing', 'medical'],
    purposes: ['livingSupport', 'childcare', 'housing', 'medical'],
    prefectures: ['北海道'],
    municipalities: ['釧路市'],
  },
  {
    label: '安中市 安中市民商品券',
    description: '物価高騰対策の商品券。対象者、金額、利用期限を確認できます。',
    href: '/grant/annaka-citizen-voucher-2026/',
    intent: '生活支援',
    observedQuery: '安中市民商品券',
    seoTitle: '安中市民商品券｜1人4,000円・利用期限',
    metaDescription: '安中市民商品券は、2026年6月1日時点で安中市に住民登録がある人へ1人4,000円分を配布。利用期限は2027年1月31日です。対象と公式確認先を掲載しています。',
    shortAnswer: '安中市民商品券は、2026年6月1日時点で安中市に住民登録がある人へ、1人4,000円分の商品券を配布する物価高騰対策です。',
    categories: ['living'],
    purposes: ['livingSupport'],
    prefectures: ['群馬県'],
    grantSlugs: ['annaka-citizen-voucher-2026'],
  },
  {
    label: '宮崎市 介護用品支給',
    description: '在宅介護に関する介護用品支給制度。対象要件と確認先を整理しています。',
    href: '/grant/miyazaki-city-nursing-equipment/',
    intent: '介護',
    observedQuery: '宮崎市介護用品支給事業',
    seoTitle: '宮崎市 介護用品支給｜年間上限10万円・対象要件',
    metaDescription: '宮崎市の介護用品支給は、在宅の要介護者を介護する家族へ紙おむつや尿取りパッドなどを支給する制度です。要介護度・世帯課税状況別の年間限度額と公式確認先を整理しています。',
    shortAnswer: '宮崎市の介護用品支給は、在宅で要介護1から5の人を介護する家族に、紙おむつや尿取りパッドなどを支給する制度です。年間限度額は要介護度と世帯の課税状況により異なり、最大10万円です。',
    categories: ['nursing'],
    purposes: ['welfare'],
    prefectures: ['宮崎県'],
    grantSlugs: ['miyazaki-city-nursing-equipment'],
  },
  {
    label: '由利本荘市 生活応援券',
    description: '市民向けの生活応援券。使用期間や公式確認先を確認できます。',
    href: '/grant/yurihonjo-life-support-voucher-2026/',
    intent: '生活支援',
    observedQuery: '由利本荘市 生活応援券',
    seoTitle: '由利本荘市生活応援券｜購入申込終了・使用期限',
    metaDescription: '由利本荘市生活応援券は、1セット5,000円で1万円分を利用できるプレミアム商品券です。購入申込は終了し、使用期限は2026年8月31日です。公式確認先を掲載しています。',
    shortAnswer: '由利本荘市生活応援券は、1セット5,000円で1万円分を利用でき、1人2セットまで購入できる商品券です。購入申込は2026年3月17日に終了し、使用期限は2026年8月31日です。',
    categories: ['living'],
    purposes: ['livingSupport'],
    prefectures: ['秋田県'],
    grantSlugs: ['yurihonjo-life-support-voucher-2026'],
  },
  {
    label: '福山市 おでかけ乗車券',
    description: '高齢者向けのバス・タクシー乗車券。交付額と対象年齢を整理しています。',
    href: '/grant/fukuyama-elderly-support/',
    intent: '介護',
    observedQuery: '福山市 おでかけ乗車券',
    seoTitle: '福山市 おでかけ乗車券｜75歳以上・年7,000円分',
    metaDescription: '福山市のおでかけ乗車券は、10月1日時点で市内に住所がある満75歳以上の人が対象。年7,000円分を交付し、バス・タクシー共通券とバス専用券に分かれます。',
    shortAnswer: '福山市のおでかけ乗車券は、10月1日時点で市内に住所がある満75歳以上の人へ、年7,000円分の乗車券を交付する外出支援です。',
    categories: ['nursing'],
    purposes: ['welfare'],
    prefectures: ['広島県'],
    grantSlugs: ['fukuyama-elderly-support'],
  },
  {
    label: '渋谷区 立ち退きに伴う住み替え家賃補助',
    description: '立ち退きで区内へ転居する対象世帯への家賃補助と転居一時金を確認できます。',
    href: '/grant/shibuya-housing-purchase/',
    intent: '住まい',
    observedQuery: '渋谷区 住み替え',
    seoTitle: '渋谷区の住み替え家賃補助｜対象世帯・支援内容',
    metaDescription: '渋谷区の立ち退きに伴う住み替え家賃補助は、対象世帯へ月額上限1万円の家賃補助と、新家賃3か月分相当までの転居一時金を支給します。対象と公式確認先を整理しています。',
    shortAnswer: '渋谷区の住み替え家賃補助は、取り壊し等で立ち退きを求められた高齢者・障害者・ひとり親世帯等を対象に、月額上限1万円の家賃補助と転居一時金を支給する制度です。',
    categories: ['housing'],
    purposes: ['housing'],
    prefectures: ['東京都'],
    grantSlugs: ['shibuya-housing-purchase'],
  },
  {
    label: '日本学生支援機構・奨学金関連',
    description: '給付奨学金と貸与奨学金の違い、対象、申込時期、公式確認先を整理しています。',
    href: '/grant/jasso-shougakukin/',
    intent: '学び',
    observedQuery: '日本学生支援機構 奨学金',
    seoTitle: 'JASSO奨学金｜給付型・第一種・第二種の違い',
    metaDescription: 'JASSO（日本学生支援機構）の奨学金には、返済不要の給付型、無利子の第一種、利子付きの第二種があります。対象、申込時期、公式確認先を整理しています。',
    shortAnswer: 'JASSOの奨学金には返済不要の給付型と、返済が必要な第一種・第二種があります。申請は原則として在学中または進学予定の学校を通じて行います。',
    categories: ['education'],
    purposes: ['education'],
    grantSlugs: ['jasso-shougakukin'],
  },
  {
    label: '奈良市 子ども医療費助成',
    description: '高校生世代までの対象範囲と助成内容、公式確認先を整理しています。',
    href: '/grant/nara-city-child-medical/',
    intent: '子育て',
    observedQuery: '奈良市 子ども医療費助成',
    seoTitle: '奈良市 子ども医療費助成｜高校生世代まで',
    metaDescription: '奈良市の子ども医療費助成は、健康保険に加入する18歳年度末までの子どもが対象です。助成内容、申請方法、奈良市の公式確認先を整理しています。',
    shortAnswer: '奈良市の子ども医療費助成は、健康保険に加入している18歳年度末までの高校生世代の子どもを対象に、保険診療の自己負担額を助成する制度です。',
    categories: ['childcare'],
    purposes: ['childcare'],
    prefectures: ['奈良県'],
    grantSlugs: ['nara-city-child-medical'],
  },
  {
    label: '四日市市 子宮頸がん検診',
    description: '市が行う検診の対象、費用、実施期間と公式確認先を整理しています。',
    href: '/grant/yokkaichi-cancer-screening/',
    intent: '医療',
    observedQuery: '子宮頸がん検診 四日市',
    seoTitle: '四日市市のがん検診｜対象年齢・費用・受診方法',
    metaDescription: '四日市市が実施する令和8年度のがん検診について、胃がん・大腸がん・肺がん・子宮頸がん・乳がんなどの対象年齢、費用、公式確認先を整理しています。',
    shortAnswer: '四日市市では、市内在住で各検診の対象年齢に該当する人を対象に、胃がん・大腸がん・肺がん・子宮頸がん・乳がんなどの検診を実施しています。',
    categories: ['medical'],
    purposes: ['medical'],
    prefectures: ['三重県'],
    grantSlugs: ['yokkaichi-cancer-screening'],
  },
  {
    label: '西原町 かなまる商品券',
    description: '町民向け商品券の配布額、対象基準日、利用期間を確認できます。',
    href: '/grant/nishihara-kanamaru-voucher-2026/',
    intent: '生活支援',
    observedQuery: '西原町 かなまる商品券',
    seoTitle: '西原町 かなまる商品券｜1人1万円・利用期限',
    metaDescription: '西原町かなまる商品券は、2026年3月1日時点で住民登録のある人へ1人1万円分を配布。利用期間は2026年6月1日から10月31日までです。',
    shortAnswer: '西原町かなまる商品券は、2026年3月1日時点で西原町の住民基本台帳に登録されている人へ、1人1万円分の商品券を配布する生活支援事業です。',
    categories: ['living'],
    purposes: ['livingSupport'],
    prefectures: ['沖縄県'],
    grantSlugs: ['nishihara-kanamaru-voucher-2026'],
  },
  {
    label: '名取市 子ども医療費助成',
    description: '18歳年度末までの対象範囲、助成内容、申請期限を整理しています。',
    href: '/grant/natori-child-medical/',
    intent: '子育て',
    observedQuery: '名取市 子ども医療費助成',
    seoTitle: '名取市 子ども医療費助成｜18歳年度末まで',
    metaDescription: '名取市の子ども医療費助成は、0歳から18歳年度末までの子どもが対象です。健康保険適用診療の自己負担額、申請時期、公式確認先を整理しています。',
    shortAnswer: '名取市の子ども医療費助成は、名取市に住民登録がある0歳から18歳年度末までの子どもについて、健康保険適用診療の自己負担額を助成する制度です。',
    categories: ['childcare'],
    purposes: ['childcare'],
    prefectures: ['宮城県'],
    grantSlugs: ['natori-child-medical'],
  },
  {
    label: '小松市 こども医療費助成',
    description: '18歳年度末までの対象範囲、窓口負担、申請・相談先を整理しています。',
    href: '/grant/komatsu-official-001-014-2026-ishikawa/',
    intent: '医療',
    observedQuery: '小松市 医療費 相談',
    seoTitle: '小松市 こども医療費助成｜18歳年度末まで・窓口無料',
    metaDescription: '小松市のこども医療費助成は、健康保険に加入する0歳から18歳年度末までの子どもが対象です。保険診療分は窓口負担無料。受給者証の交付申請・償還払いと公式相談先を整理しています。',
    shortAnswer: '小松市のこども医療費助成は、市内に住民登録があり健康保険に加入する0歳から18歳年度末までの子どもを対象に、保険診療分の窓口負担を無料にする制度です。',
    categories: ['medical', 'childcare'],
    purposes: ['medical', 'childcare'],
    prefectures: ['石川県'],
    municipalities: ['小松市'],
    grantSlugs: ['komatsu-official-001-014-2026-ishikawa'],
  },
  {
    label: '小樽市 こども医療費助成',
    description: '18歳年度末までの対象範囲、初診時の自己負担、申請期限を整理しています。',
    href: '/grant/otaru-child-medical/',
    intent: '医療',
    observedQuery: '小樽市 医療費 相談',
    seoTitle: '小樽市 こども医療費助成｜18歳年度末まで・自己負担',
    metaDescription: '小樽市のこども医療費助成は、18歳年度末までの子どもが対象です。医科580円・歯科510円の初診時一部負担金、所得制限、受給者証申請と公式相談先を整理しています。',
    shortAnswer: '小樽市のこども医療費助成は、18歳年度末までの子どもの入院・通院を対象に、医科580円・歯科510円の初診時一部負担金などを除く保険診療分を助成します。',
    categories: ['medical', 'childcare'],
    purposes: ['medical', 'childcare'],
    prefectures: ['北海道'],
    municipalities: ['小樽市'],
    grantSlugs: ['otaru-child-medical'],
  },
  {
    label: '各務原市 こども医療費助成',
    description: '高校生年代までの対象範囲、窓口負担、申請期限を整理しています。',
    href: '/grant/kakamigahara-child-medical/',
    intent: '医療',
    observedQuery: '各務原市 医療費 相談',
    seoTitle: '各務原市 こども医療費助成｜18歳年度末まで・申請期限',
    metaDescription: '各務原市のこども医療費助成は、18歳年度末までの子どもが対象です。岐阜県内の保険内診療分は窓口無料。出生日・転入日から30日以内の申請と公式相談先を整理しています。',
    shortAnswer: '各務原市のこども医療費助成は、18歳年度末までの子どもの保険内診療分を助成する制度です。福祉医療費受給者証は出生日または転入日から30日以内に申請します。',
    categories: ['medical', 'childcare'],
    purposes: ['medical', 'childcare'],
    prefectures: ['岐阜県'],
    municipalities: ['各務原市'],
    grantSlugs: ['kakamigahara-child-medical'],
  },
  {
    label: '寝屋川市 子ども医療費助成',
    description: '高校生世代までの対象範囲、助成内容、公式相談先を整理しています。',
    href: '/grant/neyagawa-child-medical/',
    intent: '医療',
    observedQuery: '寝屋川市 医療費 相談',
    seoTitle: '寝屋川市 子ども医療費助成｜高校生世代まで・相談先',
    metaDescription: '寝屋川市の子ども医療費助成は、市内在住で健康保険に加入する高校生世代までが対象です。保険診療分の助成内容、医療証の手続き、公式相談先を整理しています。',
    shortAnswer: '寝屋川市の子ども医療費助成は、市内に住民登録があり健康保険に加入する高校生世代までの子どもを対象に、保険診療分の自己負担額を助成する制度です。',
    categories: ['medical', 'childcare'],
    purposes: ['medical', 'childcare'],
    prefectures: ['大阪府'],
    municipalities: ['寝屋川市'],
    grantSlugs: ['neyagawa-child-medical'],
  },
  {
    label: '廿日市市 各種医療費助成',
    description: '目的別に案内されている医療費助成と公式相談先を確認できます。',
    href: '/grant/hiroshima-official-003-033-2026/',
    intent: '医療',
    observedQuery: '廿日市市 医療費 相談',
    seoTitle: '廿日市市の医療費助成｜目的別の制度・相談先',
    metaDescription: '廿日市市が目的別に案内する各種医療費助成について、制度の確認先と公式相談先を整理しています。対象や助成内容は各制度の公式案内をご確認ください。',
    shortAnswer: '廿日市市の各種医療費助成について、目的別の制度一覧と公式確認先を案内しています。対象となる制度と詳しい条件は公式ページでご確認ください。',
    categories: ['medical'],
    purposes: ['medical'],
    prefectures: ['広島県'],
    municipalities: ['廿日市市'],
    grantSlugs: ['hiroshima-official-003-033-2026'],
  },
  {
    label: '松山市 子ども医療費助成',
    description: '18歳年度末までの対象範囲、資格申請、公式相談先を整理しています。',
    href: '/grant/matsuyama-child-medical/',
    intent: '医療',
    observedQuery: '松山市 医療費 相談',
    seoTitle: '松山市 子ども医療費助成｜18歳年度末まで・相談先',
    metaDescription: '松山市の子ども医療費助成は、健康保険に加入する18歳年度末までの子どもが対象です。資格申請、電子申請・郵送対応と公式相談先を整理しています。',
    shortAnswer: '松山市の子ども医療費助成は、健康保険に加入する18歳年度末までの子どもが対象です。助成を受けるには資格申請が必要です。',
    categories: ['medical', 'childcare'],
    purposes: ['medical', 'childcare'],
    prefectures: ['愛媛県'],
    municipalities: ['松山市'],
    grantSlugs: ['matsuyama-child-medical'],
  },
  {
    label: '前橋市 子どもの福祉医療費助成',
    description: '高校生世代までの対象範囲、自己負担、公式相談先を整理しています。',
    href: '/grant/maebashi-child-medical/',
    intent: '医療',
    observedQuery: '前橋市 医療費 相談',
    seoTitle: '前橋市 子どもの医療費助成｜高校生世代まで・相談先',
    metaDescription: '前橋市の福祉医療費助成は、高校生世代までの子どもが対象です。所得制限・受診時自己負担の扱い、受給資格者証と公式相談先を整理しています。',
    shortAnswer: '前橋市の子どもの福祉医療費助成は、18歳年度末までの高校生世代を対象に医療費を助成する制度です。受給資格者証の交付申請が必要です。',
    categories: ['medical', 'childcare'],
    purposes: ['medical', 'childcare'],
    prefectures: ['群馬県'],
    municipalities: ['前橋市'],
    grantSlugs: ['maebashi-child-medical'],
  },
  {
    label: '彦根市 子どもの医療費助成',
    description: '高校生世代までの対象範囲、自己負担、申請方法を整理しています。',
    href: '/grant/hikone-child-medical/',
    intent: '医療',
    observedQuery: '彦根市 医療費 相談',
    seoTitle: '彦根市 子どもの医療費助成｜高校生世代まで・相談先',
    metaDescription: '彦根市の子どもの医療費助成は、乳幼児から高校生世代までが対象です。保険診療内の自己負担なし、所得制限、受給券申請と公式相談先を整理しています。',
    shortAnswer: '彦根市の子どもの医療費助成は、乳幼児から18歳年度末までの高校生世代を対象に、保険診療内の自己負担なしとする制度です。',
    categories: ['medical', 'childcare'],
    purposes: ['medical', 'childcare'],
    prefectures: ['滋賀県'],
    municipalities: ['彦根市'],
    grantSlugs: ['hikone-child-medical'],
  },
  {
    label: '岩国市 こども医療費助成制度',
    description: '小学生・中学生などの対象範囲、助成対象外の費用、公式相談先を整理しています。',
    href: '/grant/iwakuni-child-medical-aid/',
    intent: '医療',
    observedQuery: '岩国市 医療費 相談',
    seoTitle: '岩国市 こども医療費助成｜小中学生・公式相談先',
    metaDescription: '岩国市のこども医療費助成は、市内在住で健康保険に加入する小学生・中学生などが対象です。健康保険適用の自己負担額、対象外費用、公式相談先を整理しています。',
    shortAnswer: '岩国市のこども医療費助成は、市内に住所があり健康保険に加入する小学生・中学生などを対象に、健康保険適用の医療費自己負担額を助成する制度です。',
    categories: ['medical', 'childcare'],
    purposes: ['medical', 'childcare'],
    prefectures: ['山口県'],
    grantSlugs: ['iwakuni-child-medical-aid'],
  },
  {
    label: '唐津市 老朽危険空き家等除却促進事業',
    description: '危険な空き家の除却支援。事前調査、申込期間、公式確認先を整理しています。',
    href: '/grant/saga-official-001-014-2026/',
    intent: '住まい',
    observedQuery: '唐津市 家屋解体',
    seoTitle: '唐津市の危険空き家除却補助｜上限50万円・申込期限',
    metaDescription: '唐津市は、老朽化して危険な空き家などの除却費用を上限50万円まで補助しています。申込期限の延長案内、対象、公式確認先を整理しています。',
    shortAnswer: '唐津市は、老朽化して危険な空き家などを除却する費用を上限50万円まで補助しています。対象条件と申込期限は公式案内でご確認ください。',
    categories: ['housing'],
    purposes: ['housing', 'livingSupport'],
    prefectures: ['佐賀県'],
    grantSlugs: ['saga-official-001-014-2026'],
  },
  {
    label: '越谷市 人間ドック検診料助成',
    description: '人間ドック検診料の助成額、対象となる保険加入者、申請期限を整理しています。',
    href: '/grant/koshigaya-health-checkup-subsidy/',
    intent: '医療',
    observedQuery: '越谷市 人間ドック 補助 金',
    seoTitle: '越谷市 人間ドック助成｜上限1万円・対象者',
    metaDescription: '越谷市の人間ドック検診料助成は、国民健康保険に加入する受診年度35歳以上の人や後期高齢者医療被保険者が対象です。上限1万円、年度内1回の助成要件と公式確認先を整理しています。',
    shortAnswer: '越谷市の人間ドック検診料助成は、対象となる国民健康保険加入者や後期高齢者医療被保険者へ、検診料を上限1万円、一年度に一回助成する制度です。',
    categories: ['medical'],
    purposes: ['medical'],
    prefectures: ['埼玉県'],
    grantSlugs: ['koshigaya-health-checkup-subsidy'],
  },
  {
    label: '美濃市 子育て世帯住宅支援事業補助金',
    description: '子育て世帯・若い夫婦世帯の住宅取得や空き家リフォームに対する支援です。',
    href: '/grant/gifu-official-002-013-2026/',
    intent: '住まい',
    observedQuery: '美濃市 補助金 リフォーム',
    seoTitle: '美濃市 子育て世帯住宅支援｜住宅取得・リフォーム',
    metaDescription: '美濃市の子育て世帯住宅支援事業補助金は、住宅取得や空き家購入・リフォームを行う子育て世帯・若い夫婦世帯が対象です。基本額20万円と加算、契約・申請要件を整理しています。',
    shortAnswer: '美濃市の子育て世帯住宅支援事業補助金は、市内で住宅取得または空き家購入・リフォームを行う対象世帯へ、基本額20万円に転入者・子どもなどの加算を行う制度です。',
    categories: ['housing'],
    purposes: ['housing'],
    prefectures: ['岐阜県'],
    municipalities: ['美濃市'],
    grantSlugs: ['gifu-official-002-013-2026'],
  },
  {
    label: '名護市 就学援助制度',
    description: '児童生徒と保護者向けの就学援助。対象要件と公式相談先を確認できます。',
    href: '/grant/okinawa-official-002-016-2026/',
    intent: '学び',
    observedQuery: '名護市 教育費 相談',
    seoTitle: '名護市 就学援助制度｜対象要件・教育費の相談先',
    metaDescription: '名護市の就学援助制度は、市内の児童生徒と保護者を対象とする教育費の支援制度です。対象要件、支援内容、申請方法は名護市の公式案内で確認できます。',
    shortAnswer: '名護市には、公式要件を満たす児童生徒と保護者を対象とした就学援助制度があります。支援内容や申請方法は、名護市の公式案内でご確認ください。',
    categories: ['education'],
    purposes: ['education'],
    prefectures: ['沖縄県'],
    municipalities: ['名護市'],
    grantSlugs: ['okinawa-official-002-016-2026'],
  },
  {
    label: '宜野湾市 就学援助制度',
    description: '小中学生の学用品費、修学旅行費、学校給食費などの援助を確認できます。',
    href: '/grant/ginowan-school-lunch-subsidy/',
    intent: '学び',
    observedQuery: '宜野湾市 教育費 相談',
    seoTitle: '宜野湾市 就学援助制度｜学用品費・学校給食費',
    metaDescription: '宜野湾市の就学援助制度は、公式要件を満たす小中学生の家庭へ、学用品費、修学旅行費、学校給食費などを援助します。申請期限と公式相談先を整理しています。',
    shortAnswer: '宜野湾市の就学援助制度は、経済的理由により就学が困難な小中学生の家庭へ、学用品費、修学旅行費、学校給食費などを援助する制度です。',
    categories: ['childcare', 'education'],
    purposes: ['education', 'childcare'],
    prefectures: ['沖縄県'],
    municipalities: ['宜野湾市'],
    grantSlugs: ['ginowan-school-lunch-subsidy'],
  },
  {
    label: '東根市 子育て支援医療給付制度',
    description: '18歳年度末までの対象範囲、窓口負担、公式相談先を整理しています。',
    href: '/grant/higashine-child-medical-expense-subsidy-2026/',
    intent: '医療',
    observedQuery: '東根市 医療費 相談',
    seoTitle: '東根市 子育て支援医療給付｜18歳年度末まで・窓口負担なし',
    metaDescription: '東根市の子育て支援医療給付制度は、医療保険に加入する18歳年度末までの子どもが対象です。通院・入院の保険診療分に窓口負担がない助成内容、医療証の手続き、公式相談先を整理しています。',
    shortAnswer: '東根市の子育て支援医療給付制度は、出生から18歳年度末までの子どもを対象に、通院・入院とも保険診療分の窓口負担をなくす制度です。',
    categories: ['medical', 'childcare'],
    purposes: ['medical', 'childcare'],
    prefectures: ['山形県'],
    municipalities: ['東根市'],
    grantSlugs: ['higashine-child-medical-expense-subsidy-2026'],
  },
  {
    label: '阿賀野市 奨学金制度',
    description: '無利子の奨学金貸付について、受付・審査時期と返還方法を確認できます。',
    href: '/grant/agano-scholarship/',
    intent: '学び',
    observedQuery: '阿賀野市 教育資金 相談',
    seoTitle: '阿賀野市 奨学金制度｜無利子貸付・返済方法',
    metaDescription: '阿賀野市の奨学金制度は、経済的理由により修学が困難な学生へ奨学金を無利子で貸し付けます。返済が必要な貸付制度です。受付・審査時期、返還方法、公式相談先を整理しています。',
    shortAnswer: '阿賀野市の奨学金制度は、公式要件を満たす学生・保護者を対象とする無利子の貸付制度です。給付型ではなく返済が必要です。',
    categories: ['education'],
    purposes: ['education'],
    prefectures: ['新潟県'],
    municipalities: ['阿賀野市'],
    grantSlugs: ['agano-scholarship'],
  },
  {
    label: '八代市 奨学資金貸付制度',
    description: '高校・大学などへの進学・在学者向けの無利息貸付。貸付額と返還条件を確認できます。',
    href: '/grant/kumamoto-official-001-027-2026/',
    intent: '学び',
    observedQuery: '八代市 教育資金 相談',
    seoTitle: '八代市 奨学資金貸付制度｜月額上限5万円・無利息',
    metaDescription: '八代市の奨学資金貸付制度は、高校・高専・専門学校・短大・大学へ進学・在学する対象者へ月額2万円〜5万円以内を無利息で貸し付けます。返済が必要な制度です。',
    shortAnswer: '八代市の奨学資金は、高校・大学などへ進学または在学する対象者へ、月額2万円から5万円以内を無利息で貸し付ける制度です。給付型ではなく返済が必要です。',
    categories: ['education'],
    purposes: ['education'],
    prefectures: ['熊本県'],
    municipalities: ['八代市'],
    grantSlugs: ['kumamoto-official-001-027-2026'],
  },
  {
    label: '直方市 就学援助',
    description: '小中学校で必要な学用品費・学校給食費などの援助と申請方法を確認できます。',
    href: '/grant/fukuoka-official-001-058-2026/',
    intent: '学び',
    observedQuery: '直方市 教育費 相談',
    seoTitle: '直方市 就学援助｜学用品費・学校給食費・申請方法',
    metaDescription: '直方市の就学援助は、対象となる小中学生の保護者へ学用品費、学校給食費、修学旅行費などを援助します。随時受付の申請方法と公式相談先を整理しています。',
    shortAnswer: '直方市の就学援助は、経済的な理由で小中学校への就学にお困りの家庭へ、学用品費、学校給食費、修学旅行費などの一部を援助する制度です。申請は随時受け付けています。',
    categories: ['education'],
    purposes: ['education'],
    prefectures: ['福岡県'],
    municipalities: ['直方市'],
    grantSlugs: ['fukuoka-official-001-058-2026'],
  },
  {
    label: '子育て・出産の給付金',
    description: '児童手当、出産、医療費など、家族向けの制度をまとめて探せます。',
    href: '/category/childcare/',
    intent: '子育て',
    observedQuery: '子育て 出産 補助金',
    categories: ['childcare'],
    purposes: ['childcare'],
  },
];

export function getSearchConsoleOpportunitiesForCategory(category: GrantCategory, limit = 4): SearchConsoleOpportunity[] {
  return SEARCH_CONSOLE_OPPORTUNITIES
    .filter((item) => item.categories.includes(category))
    .slice(0, limit);
}

export function getSearchConsoleOpportunitiesForPrefecture(prefecture: string, limit = 4): SearchConsoleOpportunity[] {
  return SEARCH_CONSOLE_OPPORTUNITIES
    .filter((item) => item.prefectures?.includes(prefecture))
    .slice(0, limit);
}

export function getSearchConsoleOpportunitiesForMunicipality(
  prefecture: string,
  municipality: string,
  limit = 4,
): SearchConsoleOpportunity[] {
  return SEARCH_CONSOLE_OPPORTUNITIES
    .filter((item) =>
      item.prefectures?.includes(prefecture) && item.municipalities?.includes(municipality)
    )
    .slice(0, limit);
}

export function getSearchConsoleOpportunitiesForGrant(input: {
  slug: string;
  category: GrantCategory;
  purposes?: Purpose[];
  prefecture?: string;
}, limit = 4): SearchConsoleOpportunity[] {
  const matched = SEARCH_CONSOLE_OPPORTUNITIES
    .map((item) => {
      let score = 0;
      if (item.grantSlugs?.includes(input.slug)) score += 6;
      if (item.prefectures?.includes(input.prefecture ?? '')) score += 2;
      if (item.categories.includes(input.category)) score += 2;
      if (input.purposes?.some((purpose) => item.purposes.includes(purpose))) score += 1;
      return { item, score };
    })
    .filter(({ score }) => score > 0)
    .sort((left, right) => right.score - left.score);

  return matched.map(({ item }) => item).slice(0, limit);
}
